<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.lix</groupId>
        <artifactId>mycat-demo</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>provider</artifactId>
    <packaging>pom</packaging>
    <name>provider</name>
    <description>Dubbo 服务提供方模块</description>

    <modules>
        <module>facade</module>
        <module>common</module>
        <module>dao</module>
        <module>integration</module>
        <module>web</module>
        <module>service</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>


    <build>
        <plugins>
            <!-- Spring Boot Maven Plugin -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>
                        -javaagent:D:\tools\skywalking-agent\skywalking-agent-consumer\skywalking-agent.jar
                        -Dskywalking.agent.service_name=${project.artifactId}
                        -Dskywalking.collector.backend_service=127.0.0.1:11800
                    </jvmArguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

