spring:
  application:
    name: dubbo-consumer

  cloud:
    config:
      enabled: false

# Dubbo 配置
dubbo:
  application:
    name: dubbo-consumer
    qos-host: 127.0.0.1
    qos-port: 22223
  registry:
    address: nacos://localhost:8848
  consumer:
    timeout: 3000
    retries: 0
# 预热功能
#  provider:
#    warmup: 120000
#    weight: 100

# 服务端，服务延迟注册
#  provider:
#    delay: 3000

# 服务端口
server:
  port: 8082

